version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-holochain:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          command: |
            cd /holochain/build && nix-shell --run "cd /root/project/example-dna && CARGO_TARGET=target cargo build --release --target wasm32-unknown-unknown && dna-util -c example-dna.dna.workdir" .
  test-holochain:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          command: |
            nix-shell --run "cd example-dna/tests && npm install && npm test" /holochain/build
  build-ui:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          command: |
            nix-shell --run "cd ui && npm install && npm run lint && npm run build" /holochain/build
  test-ui:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          command: |
            nix-shell --run "cd ui && npm test && npm run e2e" /holochain/build

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-holochain
      - test-holochain:
          requires:
            - build-holochain
