version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          name: build-holochain
          command: cd /holochain/build && nix-shell --run "cd /root/project/example-dna && CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown && dna-util -c example-dna.dna.workdir/" .
      - run:
          name: test-holochain
          command: cd /holochain/build && nix-shell --run "cd /root/project/example-dna/tests && ls && npm install && ls node_modules && npm test" .
      - run:
          name: build-ui
          command: cd /holochain/build && nix-shell --run "cd /root/project/ui && npm install && npm run lint && npm run build" .
      - run:
          name: test-ui
          command: cd /holochain/build && nix-shell --run "cd /root/project/ui && npm install && npm test && npm run e2e" .

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-and-test
