---
environment_path: ".sandbox/xLDuEveDf03-TT4dOO43F"
use_dangerous_test_keystore: false
signing_service_uri: ~
encryption_service_uri: ~
decryption_service_uri: ~
dpki: ~
keystore_path: ".sandbox/xLDuEveDf03-TT4dOO43F/keystore"
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 0
network: ~
